### ISSUE TITLE
Error when initialized only from Bluemix(IBM Cloud) Runtime to IBM Cloudant

### ISSUE THREAD

**Issue by dotnsf** [apache/couchdb-nano#122]
## General Summery

Following error triggered only when run on Bluemix at : var nano = require( 'nano' )( 'https://xxxx-bluemix:yyyy@xxxx-bluemix.cloudant.com' );

When I run completely same code in my local Linux(Ubuntu 16.04), it works as expected. I see error messages only when I pushed into Bluemix and run on Bluemix.

## Error log messages

2018-09-11T10:49:28.08+0900 [APP/PROC/WEB/0] OUT > node app.js
2018-09-11T10:49:28.39+0900 [APP/PROC/WEB/0] ERR /home/vcap/app/node_modules/nano/lib/nano.js:83
2018-09-11T10:49:28.39+0900 [APP/PROC/WEB/0] ERR return function(err, response = { statusCode: 500 }, body = '') {
2018-09-11T10:49:28.39+0900 [APP/PROC/WEB/0] ERR ^
2018-09-11T10:49:28.39+0900 [APP/PROC/WEB/0] ERR SyntaxError: Unexpected token =
2018-09-11T10:49:28.39+0900 [APP/PROC/WEB/0] ERR at exports.runInThisContext (vm.js:53:16)
2018-09-11T10:49:28.39+0900 [APP/PROC/WEB/0] ERR at Module._compile (module.js:373:25)
2018-09-11T10:49:28.39+0900 [APP/PROC/WEB/0] ERR at Object.Module._extensions..js (module.js:416:10)
2018-09-11T10:49:28.39+0900 [APP/PROC/WEB/0] ERR at Module.load (module.js:343:32)
2018-09-11T10:49:28.39+0900 [APP/PROC/WEB/0] ERR at Function.Module._load (module.js:300:12)
2018-09-11T10:49:28.39+0900 [APP/PROC/WEB/0] ERR at Module.require (module.js:353:17)
2018-09-11T10:49:28.39+0900 [APP/PROC/WEB/0] ERR at require (internal/module.js:12:17)
2018-09-11T10:49:28.39+0900 [APP/PROC/WEB/0] ERR at Object. (/home/vcap/app/app.js:24:14)
2018-09-11T10:49:28.39+0900 [APP/PROC/WEB/0] ERR at Module._compile (module.js:409:26)
2018-09-11T10:49:28.39+0900 [APP/PROC/WEB/0] ERR at Object.Module._extensions..js (module.js:416:10)
2018-09-11T10:49:28.41+0900 [APP/PROC/WEB/0] ERR npm ERR! Linux 4.4.0-109-generic
2018-09-11T10:49:28.41+0900 [APP/PROC/WEB/0] ERR npm ERR! argv "/home/vcap/app/vendor/node/bin/node" "/home/vcap/app/vendor/node/bin/npm" "start"
2018-09-11T10:49:28.41+0900 [APP/PROC/WEB/0] ERR npm ERR! node v4.8.7
2018-09-11T10:49:28.41+0900 [APP/PROC/WEB/0] ERR npm ERR! npm v2.15.11
2018-09-11T10:49:28.41+0900 [APP/PROC/WEB/0] ERR npm ERR! code ELIFECYCLE
2018-09-11T10:49:28.41+0900 [APP/PROC/WEB/0] ERR npm ERR! hashchainsolo@0.0.2 start: node app.js
2018-09-11T10:49:28.41+0900 [APP/PROC/WEB/0] ERR npm ERR! Exit status 1
2018-09-11T10:49:28.41+0900 [APP/PROC/WEB/0] ERR npm ERR!
2018-09-11T10:49:28.41+0900 [APP/PROC/WEB/0] ERR npm ERR! Failed at the hashchainsolo@0.0.2 start script 'node app.js'.
2018-09-11T10:49:28.41+0900 [APP/PROC/WEB/0] ERR npm ERR! This is most likely a problem with the hashchainsolo package,
2018-09-11T10:49:28.41+0900 [APP/PROC/WEB/0] ERR npm ERR! not with npm itself.
2018-09-11T10:49:28.41+0900 [APP/PROC/WEB/0] ERR npm ERR! Tell the author that this fails on your system:
2018-09-11T10:49:28.41+0900 [APP/PROC/WEB/0] ERR npm ERR! node app.js
2018-09-11T10:49:28.41+0900 [APP/PROC/WEB/0] ERR npm ERR! You can get information on how to open an issue for this project with:
2018-09-11T10:49:28.41+0900 [APP/PROC/WEB/0] ERR npm ERR! npm bugs hashchainsolo
2018-09-11T10:49:28.41+0900 [APP/PROC/WEB/0] ERR npm ERR! Or if that isn't available, you can get their info via:
2018-09-11T10:49:28.41+0900 [APP/PROC/WEB/0] ERR npm ERR!
2018-09-11T10:49:28.41+0900 [APP/PROC/WEB/0] ERR npm ERR! npm owner ls hashchainsolo
2018-09-11T10:49:28.41+0900 [APP/PROC/WEB/0] ERR npm ERR! There is likely additional logging output above.
2018-09-11T10:49:28.42+0900 [APP/PROC/WEB/0] ERR npm ERR! Please include the following file with any support request:
2018-09-11T10:49:28.42+0900 [APP/PROC/WEB/0] ERR npm ERR! /home/vcap/app/npm-debug.log
2018-09-11T10:49:28.43+0900 [APP/PROC/WEB/0] OUT Exit status 1
2018-09-11T10:49:28.43+0900 [CELL/0] OUT Exit status 0

## Steps to Reproduce (for bugs)

1. On IBM Cloud, you need to create IBM Cloudant service instance, and obtain username(xxxx-bluemix) and password(yyyy).
2. Write a code: var nano = require( 'nano' )( 'https://xxxx-bluemix:yyyy@xxxx-bluemix.cloudant.com' );
3. Run this code on local machine. You will see it works.
4. But when you push this in Bluemix and run it on Bluemix, You will see above error on logs.

## My Environment

* Version used: nano 7.0.0
* Operating System and version (desktop or mobile): Ubuntu 16.04

**Comment by ricellis** [comment]
If you haven't resolved this already, check what version of Node.js is being used in both environments. The syntax being complained about:
```
2018-09-11T10:49:28.39+0900 [APP/PROC/WEB/0] ERR /home/vcap/app/node_modules/nano/lib/nano.js:83
2018-09-11T10:49:28.39+0900 [APP/PROC/WEB/0] ERR return function(err, response = { statusCode: 500 }, body = '') {
2018-09-11T10:49:28.39+0900 [APP/PROC/WEB/0] ERR ^
2018-09-11T10:49:28.39+0900 [APP/PROC/WEB/0] ERR SyntaxError: Unexpected token =
```
is the syntax for "default function parameters", they are supported only with Node.js >= 6

**Comment by big-r81** [comment]
I'm closing this old ticket. If it's still a problem, please reopen or create a new ticket.
