### ISSUE TITLE
Facing issue with error as statusCode: 500 while running tests 

### ISSUE THREAD

**Issue by ossdev07** [apache/couchdb-nano#150]
uname -a
Linux fdc92b8680c6 4.10.0-38-generic #42~16.04.1-Ubuntu SMP Tue Oct 10 16:33:57 UTC 2017 aarch64 aarch64 aarch64 GNU/Linux

Installed couchdb server and ran npm install to install dependencies. Facing below issue while running npm test command:

not ok 267 replication should not fail
not ok 268 replication should be scheduled
    operator: ok
    expected: true
    actual:   undefined
    at: <anonymous> (/couchdb-nano/tests/integration/database/replicator.js:41:16)
    stack: |-
      Error: replication should be scheduled
          at Test.assert [as _assert] (/couchdb-nano/node_modules/tape/lib/test.js:224:54)
          at Test.bound [as _assert] (/couchdb-nano/node_modules/tape/lib/test.js:76:32)
          at Test.assert (/couchdb-nano/node_modules/tape/lib/test.js:342:10)
          at Test.bound [as true] (/couchdb-nano/node_modules/tape/lib/test.js:76:32)
          at /couchdb-nano/tests/integration/database/replicator.js:41:16
          at Request._callback (/couchdb-nano/lib/nano.js:9:8777)
          at Request.self.callback (/couchdb-nano/node_modules/request/request.js:185:22)
          at Request.emit (events.js:182:13)
          at Request.<anonymous> (/couchdb-nano/node_modules/request/request.js:1161:10)
          at Request.emit (events.js:182:13)
  ...
Writing coverage object [/couchdb-nano/coverage/coverage.json]
Writing coverage reports at [/couchdb-nano/coverage]

**Coverage summary:**
Statements   : 84.14% ( 329/391 )
Branches     : 77.5% ( 155/200 )
Functions    : 77.78% ( 63/81 )
Lines        : 83.98% ( 325/387 )

/couchdb-nano/tests/integration/database/replicator.js:42
    assert.true(data.ok, 'replication should be scheduled')
                     ^

TypeError: Cannot read property 'ok' of undefined
    at /couchdb-nano/tests/integration/database/replicator.js:42:22
    at Request._callback (/couchdb-nano/lib/nano.js:9:8777)
    at Request.self.callback (/couchdb-nano/node_modules/request/request.js:185:22)
    at Request.emit (events.js:182:13)
    at Request.<anonymous> (/couchdb-nano/node_modules/request/request.js:1161:10)
    at Request.emit (events.js:182:13)
    at IncomingMessage.<anonymous> (/couchdb-nano/node_modules/request/request.js:1083:12)
    at Object.onceWrapper (events.js:273:13)
    at IncomingMessage.emit (events.js:187:15)
    at endReadableNT (_stream_readable.js:1085:12)

Please find below attachment of complete logs:
[couchdb-nano-aarch64-logs.txt](https://github.com/apache/couchdb-nano/files/3025216/couchdb-nano-aarch64-logs.txt)

Thanks in advance.

**Comment by ossdev07** [comment]
Team,

I have compiled couchdb 2.2.0 version from source and installed in both x86 and aarch64 platform.  Tested couchdb-nano package in both platforms. All tests are getting passed in x86 platform but facing below issue in aarch64 platform:
=============================== Coverage summary ===============================
Statements : 86.84% ( 330/380 )
Branches : 83.77% ( 160/191 )
Functions : 78.48% ( 62/79 )
Lines : 86.7% ( 326/376 )
================================================================================
/pruthvi/couchdb-nano/tests/integration/design/multiple.js:71
assert.equal(view.rows.length, 2, 'has more or less than two rows')
^

TypeError: Cannot read property 'length' of undefined
at Request.<anonymous> (/pruthvi/couchdb-nano/tests/integration/design/multiple.js:71:30)
at Request.emit (events.js:202:15)
at IncomingMessage.<anonymous> (/pruthvi/couchdb-nano/node_modules/request/request.js:1083:12)
at Object.onceWrapper (events.js:285:13)
at IncomingMessage.emit (events.js:202:15)
at endReadableNT (_stream_readable.js:1129:12)
at processTicksAndRejections (internal/process/next_tick.js:76:17)

Please find the attachment of aarch64 complete logs:
[couchdb-nano-aarch64-logs.txt](https://github.com/apache/couchdb-nano/files/3182759/couchdb-nano-updated-aarch64-logs.txt)

Please guide me in solving this issue.

Thanks in advance.

**Comment by ossdev07** [comment]
Hi, 

I started the CouchDB-server on the fedora and then run the package.
As a result, I could see the test cases are passing.
