### ISSUE TITLE
Unhandled Promise Rejection on timeout of nano.db.compact()

### ISSUE THREAD

**Issue by klues** [apache/couchdb-nano#269]
I'm using a script that should compact all my databases, looks like this:
```
const nano = require('nano')({
    "url": dbUrl.trim(),
    "requestDefaults": {"timeout": 250000}
});

const dblist = await nano.db.list().catch(err => console.log(err));
for (const dbName of dblist) {
    try {
        await nano.db.compact(dbName).catch(err => {
            console.log(err);
        });
    } catch (e) {
        console.log(e);
    }
}
```
see full script at: https://github.com/asterics/AsTeRICS-Grid/blob/master/scripts/couchDBCompact.js

## Expected Behavior
I expect the code above to:
* use a connection timeout of 250 seconds
* finish cleanly also in the case of an error since I'm catching all exceptions/rejections

## Current Behavior
* the script works for most databases
* for some databases it fails with the following error after 60 seconds (so my default timeout doesn't seem to work):
```
(node:84469) UnhandledPromiseRejectionWarning: Error: {error,timeout}
    at responseHandler (/<path>/node_modules/nano/lib/nano.js:175:20)
    at /<path>/node_modules/nano/lib/nano.js:405:13
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
```

## Steps to Reproduce (for bugs)
1. Download the script from https://github.com/asterics/AsTeRICS-Grid/blob/master/scripts/couchDBCompact.js
2. run `node couchDBCompact.js http://admin:password@localhost:5984 compact` with the correct credentials of a locally running CouchDB instance 

## Your Environment

* Version used: nano 9.0.3
* CouchDB Version: 2.2.0

**Comment by klues** [comment]
Thanks for testing!
After some more testing I think my problem were limited ressources on my server. While compacting I sometimes got the error `no db shards could be opened` and then like described above the node timeout error. I've experimented with increasing CouchDB params like [max_dbs_open](https://docs.couchdb.org/en/3.1.1/config/couchdb.html#couchdb/max_dbs_open) which made things even worse. Finally my solution was to simply slow down the process with an additional timeout like this:

```
await nano.db.compact(dbName).catch(err => {
    console.log(err);
});
await new Promise(resolve => setTimeout(() => resolve(), 5000));
```
