### ISSUE TITLE
socket hangup on db.list with large numbers of ids

### ISSUE THREAD

**Issue by SCdF** [apache/couchdb-nano#54]
## Expected Behavior
The `db.list` function should return doc metadata based on the ids you pass it, if any.

## Current Behavior
With large numbers of docs you instead get:
```
> { Error: socket hang up
    at createHangUpError (_http_client.js:254:15)
    at Socket.socketOnEnd (_http_client.js:346:23)
    at emitNone (events.js:91:20)
    at Socket.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickDomainCallback (internal/process/next_tick.js:122:9)
  name: 'Error',
  scope: 'socket',
  errid: 'request',
  code: 'ECONNRESET',
  description: 'socket hang up',
  stacktrace:
   [ 'Error: socket hang up',
     '    at createHangUpError (_http_client.js:254:15)',
     '    at Socket.socketOnEnd (_http_client.js:346:23)',
     '    at emitNone (events.js:91:20)',
     '    at Socket.emit (events.js:185:7)',
     '    at endReadableNT (_stream_readable.js:974:12)',
     '    at _combinedTickCallback (internal/process/next_tick.js:74:11)',
     '    at process._tickDomainCallback (internal/process/next_tick.js:122:9)' ] }
```

## Steps to Reproduce (for bugs)
Run this (modifying as needed for your local env etc):
```
const nano = require('nano')('http://admin:pass@localhost:5984');
nano.db.create('too-many-ids');
const db = nano.db.use('too-many-ids');

let ids = [];
for (let i = 0; i < 240; i++) {
  ids.push(`This-is-a-fake-id-${i}`);
}

let result = db.list({ids: ids}, console.log);
```

At least on my system, and in this test case, 239/240 is when the failure starts.

## Context
NB: One clear solution would be to use batching. However, I'm raising this because it seems unintentional.

## Your Environment
* Version used: Nano 6.4.0
* CouchDB used: Tested against both 1.6 and 2.0
* Operating System and version (desktop or mobile): MacOS 10.12.5

**Comment by SCdF** [comment]
This looks like it's somewhere in Request, but I'm not too familiar with this code base.

**Comment by SCdF** [comment]
Looks to be something to do with all params being put on the query string, and presumably something in the stack not liking that (perhaps CouchDB).

One option is to change [list](https://github.com/apache/couchdb-nano/blob/master/lib/nano.js#L503-L510) to put params as part of the body instead in the query string:

```patch
diff --git a/lib/nano.js b/lib/nano.js
index 19f6177..9a4a1d6 100644
--- a/lib/nano.js
+++ b/lib/nano.js
@@ -506,7 +506,7 @@ module.exports = exports = nano = function dbScope(cfg) {
         qs = {};
       }
 
-      return relax({db: dbName, path: '_all_docs', qs: qs}, callback);
+      return relax({db: dbName, path: '_all_docs', body: qs}, callback);
     }
 
     // http://docs.couchdb.org/en/latest/api/database/bulk-api.html#post--db-_all_docs
```
