### ISSUE TITLE
Cannot find module 'follow' with 6.4.1

### ISSUE THREAD

**Issue by l2fprod** [apache/couchdb-nano#61]
I'm getting:

Error: Cannot find module 'follow'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/fred/dev/mycatalog/node_modules/nano/lib/nano.js:21:14)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)

with nano 6.4.1

looking at package.json, it depends on "cloudant-follow" but require("follow") on line 21.

**Comment by jzaefferer** [comment]
Looks like https://github.com/apache/couchdb-nano/commit/0de43ee41fb502f8170c3bc6ce3f59e28a6674b5 only updated the dependency, without updating its usage.

**Comment by ccs018** [comment]
How quickly will a fix be provided?  Many users simply pull the latest version of the package and this is breaking builds.

**Comment by loay** [comment]
Issue is already fixed: pr is merged:  https://github.com/apache/couchdb-nano/pull/60

**Comment by garrensmith** [comment]
version 6.4.2 fixes this.
